// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entity.sql

package store

import (
	"context"
)

const createEntity = `-- name: CreateEntity :one
INSERT INTO entities(
  org_id,
  kind,
  namespace,
  name,
  metadata,
  spec
)
VALUES ($1,$2,$3,$4,$5,$6) 
RETURNING id, org_id, kind, namespace, name, metadata, spec, created_at, updated_at
`

type CreateEntityParams struct {
	OrgID     int64  `json:"org_id"`
	Kind      string `json:"kind"`
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
	Metadata  []byte `json:"metadata"`
	Spec      []byte `json:"spec"`
}

func (q *Queries) CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, createEntity,
		arg.OrgID,
		arg.Kind,
		arg.Namespace,
		arg.Name,
		arg.Metadata,
		arg.Spec,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Namespace,
		&i.Name,
		&i.Metadata,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEntity = `-- name: DeleteEntity :execrows
DELETE FROM entities
  WHERE org_id = $1 AND kind = $2 AND namespace = $3 and name = $4
`

type DeleteEntityParams struct {
	OrgID     int64  `json:"org_id"`
	Kind      string `json:"kind"`
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
}

func (q *Queries) DeleteEntity(ctx context.Context, arg DeleteEntityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntity,
		arg.OrgID,
		arg.Kind,
		arg.Namespace,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEntity = `-- name: GetEntity :one
SELECT id, org_id, kind, namespace, name, metadata, spec, created_at, updated_at FROM entities 
WHERE org_id = $1 AND kind = $2 and namespace = $3 and name = $4
LIMIT 1
`

type GetEntityParams struct {
	OrgID     int64  `json:"org_id"`
	Kind      string `json:"kind"`
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
}

func (q *Queries) GetEntity(ctx context.Context, arg GetEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntity,
		arg.OrgID,
		arg.Kind,
		arg.Namespace,
		arg.Name,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Namespace,
		&i.Name,
		&i.Metadata,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntitiesByKind = `-- name: ListEntitiesByKind :many
SELECT id, org_id, kind, namespace, name, metadata, spec, created_at, updated_at FROM entities
WHERE org_id = $1 and kind = $2
ORDER BY namespace, name
`

type ListEntitiesByKindParams struct {
	OrgID int64  `json:"org_id"`
	Kind  string `json:"kind"`
}

func (q *Queries) ListEntitiesByKind(ctx context.Context, arg ListEntitiesByKindParams) ([]Entity, error) {
	rows, err := q.db.Query(ctx, listEntitiesByKind, arg.OrgID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entity
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Kind,
			&i.Namespace,
			&i.Name,
			&i.Metadata,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntity = `-- name: UpdateEntity :one
UPDATE entities
SET metadata = $5, spec = $6, updated_at = now()
WHERE org_id = $1 AND kind = $2 and namespace = $3 and name = $4
RETURNING id, org_id, kind, namespace, name, metadata, spec, created_at, updated_at
`

type UpdateEntityParams struct {
	OrgID     int64  `json:"org_id"`
	Kind      string `json:"kind"`
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
	Metadata  []byte `json:"metadata"`
	Spec      []byte `json:"spec"`
}

func (q *Queries) UpdateEntity(ctx context.Context, arg UpdateEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, updateEntity,
		arg.OrgID,
		arg.Kind,
		arg.Namespace,
		arg.Name,
		arg.Metadata,
		arg.Spec,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Namespace,
		&i.Name,
		&i.Metadata,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
