// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relation.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRelation = `-- name: CreateRelation :one
INSERT INTO
relations (
    org_id,
    source_kind,
    source_namespace,
    source_name,
    relation_type,
    target_kind,
    target_namespace,
    target_name
  )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, source_kind, source_namespace, source_name, relation_type, target_kind, target_namespace, target_name, created_at
`

type CreateRelationParams struct {
	OrgID           int64  `json:"org_id"`
	SourceKind      string `json:"source_kind"`
	SourceNamespace string `json:"source_namespace"`
	SourceName      string `json:"source_name"`
	RelationType    string `json:"relation_type"`
	TargetKind      string `json:"target_kind"`
	TargetNamespace string `json:"target_namespace"`
	TargetName      string `json:"target_name"`
}

func (q *Queries) CreateRelation(ctx context.Context, arg CreateRelationParams) (Relation, error) {
	row := q.db.QueryRow(ctx, createRelation,
		arg.OrgID,
		arg.SourceKind,
		arg.SourceNamespace,
		arg.SourceName,
		arg.RelationType,
		arg.TargetKind,
		arg.TargetNamespace,
		arg.TargetName,
	)
	var i Relation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SourceKind,
		&i.SourceNamespace,
		&i.SourceName,
		&i.RelationType,
		&i.TargetKind,
		&i.TargetNamespace,
		&i.TargetName,
		&i.CreatedAt,
	)
	return i, err
}

const listRelationsBySource = `-- name: ListRelationsBySource :many
SELECT id, org_id, source_kind, source_namespace, source_name, relation_type, target_kind, target_namespace, target_name, created_at
  FROM relations
  WHERE org_id = $1 AND source_kind = $2 AND source_namespace = $3 AND source_name = $4
`

type ListRelationsBySourceParams struct {
	OrgID     int64  `json:"org_id"`
	Kind      string `json:"kind"`
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
}

func (q *Queries) ListRelationsBySource(ctx context.Context, arg ListRelationsBySourceParams) ([]Relation, error) {
	rows, err := q.db.Query(ctx, listRelationsBySource,
		arg.OrgID,
		arg.Kind,
		arg.Namespace,
		arg.Name,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Relation
	for rows.Next() {
		var i Relation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SourceKind,
			&i.SourceNamespace,
			&i.SourceName,
			&i.RelationType,
			&i.TargetKind,
			&i.TargetNamespace,
			&i.TargetName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsByTarget = `-- name: ListRelationsByTarget :many
SELECT
    id,
    org_id,
    source_kind,
    source_namespace,
    source_name,
    CASE relation_type
        WHEN 'ownedBy' THEN 'ownerOf'
        WHEN 'ownerOf' THEN 'ownedBy'
        WHEN 'dependsOn' THEN 'dependencyOf'
        WHEN 'dependencyOf' THEN 'dependsOn'
        WHEN 'partOf' THEN 'hasPart'
        WHEN 'hasPart' THEN 'partOf'
        WHEN 'providesApi' THEN 'apiConsumedBy'
        WHEN 'apiConsumedBy' THEN 'providesApi'
        WHEN 'memberOf' THEN 'hasMember'
        WHEN 'hasMember' THEN 'memberOf'
        ELSE relation_type
    END::text AS relation_type,
    target_kind,
    target_namespace,
    target_name,
    created_at
FROM relations
WHERE org_id = $1 AND target_kind = $2 AND target_namespace = $3 AND target_name = $4
`

type ListRelationsByTargetParams struct {
	OrgID     int64  `json:"org_id"`
	Kind      string `json:"kind"`
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
}

type ListRelationsByTargetRow struct {
	ID              int64              `json:"id"`
	OrgID           int64              `json:"org_id"`
	SourceKind      string             `json:"source_kind"`
	SourceNamespace string             `json:"source_namespace"`
	SourceName      string             `json:"source_name"`
	RelationType    string             `json:"relation_type"`
	TargetKind      string             `json:"target_kind"`
	TargetNamespace string             `json:"target_namespace"`
	TargetName      string             `json:"target_name"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRelationsByTarget(ctx context.Context, arg ListRelationsByTargetParams) ([]ListRelationsByTargetRow, error) {
	rows, err := q.db.Query(ctx, listRelationsByTarget,
		arg.OrgID,
		arg.Kind,
		arg.Namespace,
		arg.Name,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelationsByTargetRow
	for rows.Next() {
		var i ListRelationsByTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SourceKind,
			&i.SourceNamespace,
			&i.SourceName,
			&i.RelationType,
			&i.TargetKind,
			&i.TargetNamespace,
			&i.TargetName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
