// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package store

import (
	"context"
)

const deleteRefreshToken = `-- name: DeleteRefreshToken :execrows
DELETE FROM refresh_tokens
WHERE org_id = $1 AND user_id = $2
`

type DeleteRefreshTokenParams struct {
	OrgID  int64 `json:"org_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteRefreshToken(ctx context.Context, arg DeleteRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefreshToken, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, org_id, user_id, provider, subject, refresh_token, created_at, updated_at FROM refresh_tokens
WHERE org_id = $1 AND user_id = $2
`

type GetRefreshTokenParams struct {
	OrgID  int64 `json:"org_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, arg.OrgID, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRefreshToken = `-- name: UpsertRefreshToken :one
INSERT INTO refresh_tokens (org_id, user_id, provider, subject, refresh_token)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, user_id) DO UPDATE SET
  provider = EXCLUDED.provider,
  subject = EXCLUDED.subject,
  refresh_token = EXCLUDED.refresh_token,
  updated_at = now()
RETURNING id, org_id, user_id, provider, subject, refresh_token, created_at, updated_at
`

type UpsertRefreshTokenParams struct {
	OrgID        int64  `json:"org_id"`
	UserID       int64  `json:"user_id"`
	Provider     string `json:"provider"`
	Subject      string `json:"subject"`
	RefreshToken string `json:"refresh_token"`
}

func (q *Queries) UpsertRefreshToken(ctx context.Context, arg UpsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, upsertRefreshToken,
		arg.OrgID,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.RefreshToken,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
